#!/usr/bin/env python3
"""
Pack the lobby system icons (PNG → 4-bit indexed RGB565) into a C
source file compiled into the lobby firmware.

Usage:
    pack_icons.py <icons_dir> <out_c>

The icons directory must contain:
    nes.png  p8.png  doom.png  mpy.png

Each PNG is any size; we resize to 48x48 and quantise to a 16-colour
adaptive palette. The output C file exposes, for each icon:

    const uint16_t lobby_icon_<name>_palette[16];
    const uint8_t  lobby_icon_<name>_pixels[48 * 48 / 2];

Plus a single table `lobby_icons[]` that groups them by slot so the
grid renderer can look them up by THUMBYONE_SLOT_*.

Two pixels are packed per byte: the even pixel in the high nibble,
odd in the low. Keeps the decoder a single shift + mask per pixel.
"""

import os
import sys

from PIL import Image


ICON_W = 48
ICON_H = 48
NCOL   = 16

# The order here must match the `lobby_icons[]` table indexing in
# the emitted C file (which the renderer reads by slot id).
ICONS = [
    ("nes",  "NES"),
    ("p8",   "P8"),
    ("doom", "DOOM"),
    ("mpy",  "MPY"),
]


def rgb_to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def load_as_indexed(path: str) -> tuple[list[int], list[int]]:
    """Load `path`, resize to 48x48, quantise to 16 colours.

    Returns (palette_rgb565, pixels). `pixels` is a flat list of 48*48
    indices into the palette (0..15). `palette_rgb565` is 16 uint16
    values packed from the PNG's adaptive palette.
    """
    img = Image.open(path).convert("RGB")
    if img.size != (ICON_W, ICON_H):
        img = img.resize((ICON_W, ICON_H), Image.NEAREST)

    # `P` + Image.ADAPTIVE picks the best 16 colours for THIS image.
    # Each icon gets its own palette — sharing one across all four
    # would crush detail on whichever image is the visual outlier.
    qimg = img.quantize(colors=NCOL, method=Image.MEDIANCUT, dither=Image.NONE)

    pal_raw = qimg.getpalette()                    # [r,g,b, r,g,b, ...]
    palette = []
    for i in range(NCOL):
        r, g, b = pal_raw[i * 3:i * 3 + 3]
        palette.append(rgb_to_rgb565(r, g, b))

    pixels = list(qimg.getdata())                  # 48*48 = 2304 ints
    # Safety: every pixel must be < NCOL. PIL may emit more palette
    # slots than NCOL with some images — truncate to NCOL-1 here.
    pixels = [min(p, NCOL - 1) for p in pixels]

    return palette, pixels


def emit(icons_dir: str, out_c: str) -> None:
    sections = []
    names = []

    for name, label in ICONS:
        path = os.path.join(icons_dir, name + ".png")
        if not os.path.exists(path):
            print(f"error: missing {path}", file=sys.stderr)
            sys.exit(1)
        palette, pixels = load_as_indexed(path)

        # Pack two pixels per byte, even pixel in high nibble.
        packed = bytearray()
        for i in range(0, len(pixels), 2):
            hi = pixels[i]     & 0x0F
            lo = pixels[i + 1] & 0x0F
            packed.append((hi << 4) | lo)

        sections.append((name, label, palette, packed))
        names.append(name)

    with open(out_c, "w") as f:
        f.write(
            "/*\n"
            " * Auto-generated by ThumbyOne/tools/pack_icons.py —\n"
            f" * source: {icons_dir}\n"
            " * DO NOT EDIT BY HAND.\n"
            " *\n"
            " * Four 48x48 RGB565 system icons, 4-bit indexed. Each icon\n"
            " * has its own 16-entry palette. Two pixels per byte, even\n"
            " * pixel in the high nibble. Consumed by lobby_icons.c to\n"
            " * render the system-selector grid.\n"
            " */\n"
            "#include <stdint.h>\n"
            "#include <stddef.h>\n"
            "#include \"lobby_icons.h\"\n"
            "\n"
        )

        for name, label, palette, packed in sections:
            # Palette
            f.write(f"static const uint16_t lobby_icon_{name}_palette[{NCOL}] = {{\n")
            for i, rgb565 in enumerate(palette):
                sep = "," if i < NCOL - 1 else ""
                f.write(f"    0x{rgb565:04x}{sep}")
                if (i % 4) == 3:
                    f.write("\n")
            if (NCOL % 4) != 0:
                f.write("\n")
            f.write("};\n\n")

            # Pixels
            n_bytes = len(packed)
            f.write(f"static const uint8_t lobby_icon_{name}_pixels[{n_bytes}] = {{\n")
            for i in range(0, n_bytes, 16):
                row = packed[i:i + 16]
                f.write("    " + ", ".join(f"0x{b:02x}" for b in row) + ",\n")
            f.write("};\n\n")

        # Exported table
        f.write(f"const lobby_icon_t lobby_icons[{len(sections)}] = {{\n")
        for name, label, _palette, _packed in sections:
            esc = label.replace("\\", "\\\\").replace('"', '\\"')
            f.write(
                f"    {{ .label = \"{esc}\","
                f" .palette = lobby_icon_{name}_palette,"
                f" .pixels = lobby_icon_{name}_pixels }},\n"
            )
        f.write("};\n\n")
        f.write(f"const size_t lobby_icons_count = {len(sections)};\n")


def main() -> None:
    if len(sys.argv) != 3:
        print("usage: pack_icons.py <icons_dir> <out_c>", file=sys.stderr)
        sys.exit(1)
    icons_dir, out_c = sys.argv[1], sys.argv[2]
    emit(icons_dir, out_c)
    print(f"pack_icons: wrote {out_c}", file=sys.stderr)


if __name__ == "__main__":
    main()
