#!/usr/bin/env python3
"""
Pack a directory tree into a C source file as a byte blob plus an
entry table — the read-only data backing ThumbyOneRomVFS.

Usage:
    pack_system_rom.py <src_dir> <out_c>

Layout of the generated C file:

    const uint8_t tbyone_system_blob[] = { ... };
    const tbyone_rom_entry_t tbyone_system_entries[] = { ... };
    const size_t tbyone_system_entry_count = ...;

Each entry's `path` is relative to the mount point (i.e. the leading
"/system" is stripped — the consuming VFS sees "/", "/assets",
"/assets/font3x5.bmp", and so on). Directories are marked with
`type = 1` and have offset/length of 0. Regular files have
`type = 0` and point into the blob.

Paths are sorted lexicographically so lookups could be made
binary-search later if the table grows; current linear scan is fine
for the ~30 entries /system/ contains.
"""

import argparse
import os
import sys


def walk_tree(src_dir):
    """Yield (rel_path, is_dir, abs_path) tuples in sorted order.

    rel_path uses forward slashes and includes a leading '/'. The
    root itself is yielded as '/' with is_dir=True and no contents.
    """
    yield ("/", True, src_dir)

    def walk(d, prefix):
        entries = sorted(os.listdir(d))
        dirs = []
        files = []
        for name in entries:
            full = os.path.join(d, name)
            if os.path.isdir(full):
                dirs.append((name, full))
            else:
                files.append((name, full))
        # Files first, then dirs — arbitrary choice; keeps siblings
        # together so `ilistdir` can emit them in a natural order.
        for name, full in files:
            yield (prefix + "/" + name, False, full)
        for name, full in dirs:
            rel = prefix + "/" + name
            yield (rel, True, full)
            yield from walk(full, rel)

    # prefix = "" for items directly under src_dir so they appear
    # as "/foo" rather than "//foo".
    yield from walk(src_dir, "")


def emit(src_dir, out_c):
    entries = []     # list of (rel_path, is_dir, offset, length)
    blob = bytearray()
    for rel, is_dir, abs_path in walk_tree(src_dir):
        if is_dir:
            entries.append((rel, True, 0, 0))
        else:
            with open(abs_path, "rb") as f:
                data = f.read()
            entries.append((rel, False, len(blob), len(data)))
            blob.extend(data)

    with open(out_c, "w") as f:
        f.write(
            "/*\n"
            " * Auto-generated by ThumbyOne/tools/pack_system_rom.py —\n"
            f" * source: {src_dir}\n"
            " * DO NOT EDIT BY HAND.\n"
            " *\n"
            " * ThumbyOneRomVFS in thumbyone_rom_vfs.c consumes these\n"
            " * two exports to serve /system/ as a read-only MP VFS.\n"
            " */\n"
            "#include <stdint.h>\n"
            "#include <stddef.h>\n"
            "\n"
            "typedef struct {\n"
            "    const char *path;   /* relative to /system mount point */\n"
            "    uint32_t    offset; /* byte offset into blob (0 if dir)  */\n"
            "    uint32_t    length; /* byte length (0 if dir)            */\n"
            "    uint8_t     type;   /* 0 = file, 1 = dir                 */\n"
            "} tbyone_rom_entry_t;\n"
            "\n"
        )

        # Blob.
        f.write(f"const uint8_t tbyone_system_blob[{len(blob) if len(blob) else 1}] = {{\n")
        if len(blob) == 0:
            # C forbids zero-length arrays; emit a single zero byte
            # so the array is well-formed. tbyone_system_entry_count
            # keeps consumers from ever reading this byte.
            f.write("    0x00,\n")
        else:
            for i in range(0, len(blob), 16):
                row = blob[i:i + 16]
                f.write("    " + ", ".join(f"0x{b:02x}" for b in row) + ",\n")
        f.write("};\n\n")

        # Entry table.
        f.write(f"const tbyone_rom_entry_t tbyone_system_entries[{len(entries)}] = {{\n")
        for rel, is_dir, offset, length in entries:
            quoted = rel.replace("\\", "\\\\").replace('"', '\\"')
            f.write(
                f'    {{ "{quoted}", {offset:>8}u, {length:>8}u, '
                f'{1 if is_dir else 0} }},\n'
            )
        f.write("};\n\n")

        f.write(f"const size_t tbyone_system_entry_count = {len(entries)};\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("src", help="source directory (e.g. engine /filesystem/system)")
    ap.add_argument("out", help="output .c file path")
    args = ap.parse_args()

    if not os.path.isdir(args.src):
        print(f"error: {args.src} is not a directory", file=sys.stderr)
        sys.exit(1)

    emit(args.src, args.out)
    # Progress on stderr so CMake's output stays clean.
    total_files = sum(1 for _, is_dir, *_ in walk_tree(args.src) if not is_dir) - 0
    print(f"pack_system_rom: wrote {args.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
