/*
 * ThumbyOne lobby — system icon table + blitter.
 *
 * Four 48x48 icons (NES, P8, DOOM, MPY) are packed at build time
 * by tools/pack_icons.py from PNGs in lobby/icons/. The packer
 * emits a generated C source that defines `lobby_icons[]`; this
 * header exposes the shape + a tiny 4-bit-indexed → RGB565 blit
 * function the grid renderer calls.
 *
 * The icons live in flash rodata (~5 KB total) — far cheaper than
 * the ~18 KB a 16-bpp raw bitmap table would cost, which matters
 * because the lobby partition is only 128 KB.
 */
#ifndef THUMBYONE_LOBBY_ICONS_H
#define THUMBYONE_LOBBY_ICONS_H

#include <stdint.h>
#include <stddef.h>

#define LOBBY_ICON_W 48
#define LOBBY_ICON_H 48

typedef struct {
    const char     *label;    /* short name, e.g. "NES" */
    const uint16_t *palette;  /* 16 entries, RGB565     */
    const uint8_t  *pixels;   /* (W*H)/2 bytes, 4-bit   */
} lobby_icon_t;

/* Generated by pack_icons.py. Order: NES, P8, DOOM, MPY. */
extern const lobby_icon_t lobby_icons[];
extern const size_t       lobby_icons_count;

/* Blit `icon` onto the 128x128 framebuffer `fb` at (dst_x, dst_y),
 * decoding 4-bit indices through the icon's palette. Caller is
 * responsible for bounds-checking (the blit clips internally too
 * but callers should avoid drawing partially off-screen icons). */
void lobby_icon_draw(uint16_t *fb, const lobby_icon_t *icon,
                     int dst_x, int dst_y);

#endif
